# Generated by Django 5.0 on 2024-01-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.TextField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
