# Generated by Django 5.0.1 on 2024-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pessoa_endereco_remove_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
