# Generated by Django 5.0.1 on 2024-01-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pessoa_options_alter_pessoa_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
