# Generated by Django 5.0.1 on 2024-01-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
